In [1]:
import os
import numpy as np
import pandas as pd

In [4]:
path = 'C:\\Users\\arvra\\Documents\\UVa files\\Classes\\Fall_18\\Capstone Project\\books\\books\\a007\\bio12'
os.chdir(path)

In [24]:
files = os.listdir()
bess_file = [each for each in files if '.bess.xml' in each]

In [25]:
bess_file

['a007.bio12.bess.xml']

In [26]:
import xml.etree.ElementTree as ET
import csv

In [27]:
bess_file_read = bess_file[0]
tree = ET.parse(bess_file_read)
root = tree.getroot()

In [178]:
len(each.getchildren())

0

In [266]:
Event_Data_frame = pd.DataFrame({'para no' : [],'Event' : [],'Content': []})
Event_Data_frame

Empty DataFrame
Columns: [Content, Event, para no]
Index: []

In [269]:
a = None
a == None

True

In [268]:
for each_member in root.find('analysis'):
    if(each_member.tag == 'event'):
        sub_members = each_member.getchildren()
        
        ## textUnitRangeReference
        para_number = None
        
        
        for each in sub_members:
            
            if(each.text == None):
                continue
            
            ### Check if we have start and end tag for each of the sub tag ##
            
            ### Absence of Start and End subtag under the tags
            ### i.e. the tag corresponds to only one paragraph
            if(len(each.getchildren()) == 0):
                #print(each.tag)
                #print(each.text)
                
                if(each.tag == 'textUnitReference'):
                    para_number = each.text
                else:
                    
                    print(para_number)
                    if(para_number == None):
                        break
                    
                    
                    Event_Data_temp = pd.DataFrame({'para no' : [para_number], 'Event': each.tag,'Content': [each.text]})
                    Event_Data_frame = pd.concat([Event_Data_frame,Event_Data_temp], axis = 0)
            
            ### Presence of Start and End subtag under the tags
            ### i.e. the tag corresponds to more than one paragraph
            
            if(len(each.getchildren()) != 0 and each.tag == 'textUnitRangeReference'):
                start_para = int(each.getchildren()[0].text)
                end_para = int(each.getchildren()[1].text)+1
                
                
                for group_para in range(start_para,end_para):
                    counts_after_index = 0
                    for each_group_para in sub_members[1:len(sub_members)]:
                        
                        #print(group_para)
                        Event_Data_temp = pd.DataFrame({'para no' : [group_para],\
                                                        'Event': each_group_para.tag,\
                                                        'Content': [each_group_para.text]})
                        Event_Data_frame = pd.concat([Event_Data_frame,Event_Data_temp], axis = 0)
                        counts_after_index+= 1
                        
                for each in range(counts_after_index):
                    continue

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
None
2
2
2
2
2
2
2
2
2
2
2
2
2
2
None
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
7
7
7
7
7
7
7
7
7
7
7
7
7
7
8
8
8
8
8
9
9
9
9
9
9
None
None
13
13
13
13
13
13
13
14
14
14
14
14
14
15
15
15
15
15
15
15
15
15
15
None
None
None
None
19
None
None
25
25
25
25
25
25
26
26
26
26
26
26
27
27
28
28
28
28
28
28
28
28
28
28
28
28
29
29
29
29
29
29
29
29
29
31
31
31
31
31
31

In [263]:
Event_Data_frame

,Content,Event,para no
0,birth,type,1
0,province,locationSetting,1
0,"home, family or childhood",locationStructure,1
0,parsonage,locationStructure,1
0,1787,dateSingle,1
0,"renaming of persona, proper name",type,1
0,"education, private lessons",type,1
0,childhood or upbringing,type,1
0,writing other,type,1
0,"father, unnamed",agentType,1
0,"marriage, voluntary",type,1
0,husband,agentType,1
0,"male professional, named",agentType,1
0,childcare,type,1
0,managing,type,1
0,"travel, international",type,1
0,"calling or vocation choice, decision",type,1
0,"United States, as traveler or immigrant",locationSetting,1
0,publication,type,1
0,writing travel,type,1
0,insulting,type,1
0,scandal,type,1
0,"rage, tantrum, or outburst by persona",type,1
0,"introduction, first social encounter",type,1
0,controversy in politics,type,1
0,controversy of religious practice or affiliation,type,1
0,"introduction, first social encounter",type,2
0,controversy in politics,type,2
0,controversy of religious practice or affiliation,type,2
0,"introduction, first social encounter",type,None
...,...,...,...
0,"recognition, written praise",type,26
0,publication,type,27
0,writing travel,type,27
0,publication,type,28
0,writing novel,type,28
0,1836,dateSingle,28
0,publication,type,28
0,writing novel,type,28
0,1837,dateSingle,28
0,publication,type,28
0,writing novel,type,28
0,1838,dateSingle,28
0,publication,type,28
0,writing novel,type,28
0,1839,dateSingle,28
0,"move to new city, town, or village",type,29
0,escape,type,29
0,retirement from job or position,type,29
0,Italy,locationSetting,29
0,1844,dateSingle,29
0,return to work,type,29
0,publication,type,29
0,writing novel,type,29
0,1851,dateSingle,29
0,"death, persona's",type,31
0,city,locationSetting,31
0,Italy,locationSetting,31
0,"recognition, spoken praise",type,31
0,inheriting,type,31
0,"son, named",agentType,31

In [229]:
print(Event_Data_frame.shape)
len(np.unique(Event_Data_frame.Content))
Event_Data_frame

(205, 3)

,Content,Event,para no
0,birth,type,1
0,province,locationSetting,1
0,"home, family or childhood",locationStructure,1
0,parsonage,locationStructure,1
0,1787,dateSingle,1
0,"renaming of persona, proper name",type,1
0,"education, private lessons",type,1
0,childhood or upbringing,type,1
0,writing other,type,1
0,"father, unnamed",agentType,1
0,"marriage, voluntary",type,1
0,husband,agentType,1
0,"male professional, named",agentType,1
0,childcare,type,1
0,managing,type,1
0,"travel, international",type,1
0,"calling or vocation choice, decision",type,1
0,"United States, as traveler or immigrant",locationSetting,1
0,publication,type,1
0,writing travel,type,1
0,insulting,type,1
0,scandal,type,1
0,"rage, tantrum, or outburst by persona",type,1
0,"introduction, first social encounter",type,None
0,controversy in politics,type,None
0,controversy of religious practice or affiliation,type,None
0,Sunday churchgoing or sabbath,type,2
0,selling,type,2
0,sailing,type,2
0,scandal,type,2
...,...,...,...
0,"recognition, written praise",type,26
0,publication,type,27
0,writing travel,type,27
0,publication,type,28
0,writing novel,type,28
0,1836,dateSingle,28
0,publication,type,28
0,writing novel,type,28
0,1837,dateSingle,28
0,publication,type,28
0,writing novel,type,28
0,1838,dateSingle,28
0,publication,type,28
0,writing novel,type,28
0,1839,dateSingle,28
0,"move to new city, town, or village",type,29
0,escape,type,29
0,retirement from job or position,type,29
0,Italy,locationSetting,29
0,1844,dateSingle,29
0,return to work,type,29
0,publication,type,29
0,writing novel,type,29
0,1851,dateSingle,29
0,"death, persona's",type,31
0,city,locationSetting,31
0,Italy,locationSetting,31
0,"recognition, spoken praise",type,31
0,inheriting,type,31
0,"son, named",agentType,31

In [140]:
sub_members = each_member.getchildren()
sub_members

[<Element 'textUnitReference' at 0x0000016C43F7CEA8>,
 <Element 'type' at 0x0000016C43F7CEF8>]

In [138]:
a = root.find('analysis')[20]
print(a)
print(a.getchildren()[0])
a.getchildren()

<Element 'event' at 0x0000016C43F3E9F8>
<Element 'textUnitRangeReference' at 0x0000016C43F3EA48>

[<Element 'textUnitRangeReference' at 0x0000016C43F3EA48>,
 <Element 'type' at 0x0000016C43F3EB38>,
 <Element 'type' at 0x0000016C43F3EB88>,
 <Element 'type' at 0x0000016C43F3EBD8>]

In [ ]:
tree = ET.parse("resident_data.xml")
root = tree.getroot()

# open a file for writing

Resident_data = open('/tmp/ResidentData.csv', 'w')

# create the csv writer object

csvwriter = csv.writer(Resident_data)
resident_head = []

count = 0
for member in root.findall('Resident'):
	resident = []
	address_list = []
	if count == 0:
		name = member.find('Name').tag
		resident_head.append(name)
		PhoneNumber = member.find('PhoneNumber').tag
		resident_head.append(PhoneNumber)
		EmailAddress = member.find('EmailAddress').tag
		resident_head.append(EmailAddress)
		Address = member[3].tag
		resident_head.append(Address)
		csvwriter.writerow(resident_head)
		count = count + 1

	name = member.find('Name').text
	resident.append(name)
	PhoneNumber = member.find('PhoneNumber').text
	resident.append(PhoneNumber)
	EmailAddress = member.find('EmailAddress').text
	resident.append(EmailAddress)
	Address = member[3][0].text
	address_list.append(Address)
	City = member[3][1].text
	address_list.append(City)
	StateCode = member[3][2].text
	address_list.append(StateCode)
	PostalCode = member[3][3].text
	address_list.append(PostalCode)
	resident.append(address_list)
	csvwriter.writerow(resident)
Resident_data.close()