In [25]:
import xml.etree.ElementTree as ET
import re
data = open (os.getcwd() + '/bio12/a007bio12.xml',"rb")
tree = ET.parse (data)

In [26]:
a007_data = open('a007.csv', 'w')

In [27]:
root=tree.getroot()
import csv
csvwriter = csv.writer(a007_data)
a007_head = []

In [76]:
member = root.find('div2')
para_text = {}


for each in member:
    if(each.tag == 'p'):
        para_text['Para_no:'+each.get('n')] = each.text

In [156]:
import pandas as pd
d1=pd.DataFrame.from_dict(data = para_text, orient = 'index')
d1

                                                            0
Para_no:1    FRANCES MILTON, so well known in English lite...
Para_no:2    That Mrs. Trollope's prejudices sometimes pre...
Para_no:3    Mrs. Trollope's animadversions are obsolete o...
Para_no:4    "This lady," she says, "shall be the wife of ...
Para_no:5    "She rises, and her first hour is spent in th...
Para_no:6   A harmless day, after all! No doubt such days ...
Para_no:7    After an unsuccessful attempt to make a home ...
Para_no:8   Three years later she produced her "Paris and ...
Para_no:9    Mrs. Trollope records as an historical and no...
Para_no:10   Mrs. Trollope preserves two other words, whic...
Para_no:11   That Mrs. Trollope had no sympathy with the R...
Para_no:12   In truth, she is seldom happy in her literary...
Para_no:13   But from literature let us turn to society, i...
Para_no:14   To one of the worst enemies of the old-fashio...
Para_no:15   In 1835 the Parisians sometimes fell to blows...
Para_no:16   Of the numerous suicides which half a century...
Para_no:17   But instead, the elder of the two began by de...
Para_no:18   The landlord was furious. He did not believe ...
Para_no:19  The following day, impelled half by a wish to ...
Para_no:20   On a small table in the room lay several pape...
Para_no:21  It is a pity that their yearning for posthumou...
Para_no:22   We have hinted that Mrs. Trollope's strength ...
Para_no:23  When she diverts her thoughts, she says, from ...
Para_no:24   How vain are all the efforts which man is abl...
Para_no:25  In the opinion of one French critic, the book ...
Para_no:26  Everywhere, moreover, as one of her translator...
Para_no:27   France was not the only field of study which ...
Para_no:28  Our business in these pages is with Mrs. Troll...
Para_no:29   In 1844 the industrious satirist, who would h...
Para_no:30  This clever and industrious woman died at Flor...

In [91]:
member = root.find('teiHeader')

In [113]:


book_title = member.getchildren()[0].getchildren()[0].getchildren()[0].text
author = member.getchildren()[0].getchildren()[0].getchildren()[1].text
publisher = member.getchildren()[0].getchildren()[1].getchildren()[0].text
publisher2=member.getchildren()[0].getchildren()[1].getchildren()[1].text

In [129]:
bio_id=root.getchildren()[1].get('id')

In [143]:
text_type=root.getchildren()[1].get('type')

In [144]:
bio_title=root.getchildren()[1].getchildren()[0].getchildren()[0].text.strip()

In [145]:
d = {'Book_title':book_title,'Author':author, 'Publisher1':publisher, 'Publisher2':publisher2, 'Biography_id':bio_id, 'Text_type':text_type, 'Biography_title':bio_title}

In [149]:
df = pd.DataFrame(d, index=[0])

In [150]:
df

,Book_title,Author,Publisher1,Publisher2,Biography_id,Text_type,Biography_title
0,Celebrated Women Travellers of the Nineteenth ...,William Henry Davenport Adams,Sonnenschein,Dutton,bio12,chapter,MRS. TROLLOPE

In [155]:
combined_df = d1.append(d, ignore_index=True)

In [153]:
combined_df

,0,Author,Biography_id,Biography_title,Book_title,Publisher1,Publisher2,Text_type
0,"FRANCES MILTON, so well known in English lite...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,That Mrs. Trollope's prejudices sometimes pre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mrs. Trollope's animadversions are obsolete o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""This lady,"" she says, ""shall be the wife of ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"""She rises, and her first hour is spent in th...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"A harmless day, after all! No doubt such days ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,After an unsuccessful attempt to make a home ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Three years later she produced her ""Paris and ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Mrs. Trollope records as an historical and no...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"Mrs. Trollope preserves two other words, whic...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,That Mrs. Trollope had no sympathy with the R...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"In truth, she is seldom happy in her literary...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"But from literature let us turn to society, i...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,To one of the worst enemies of the old-fashio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,In 1835 the Parisians sometimes fell to blows...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Of the numerous suicides which half a century...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"But instead, the elder of the two began by de...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,The landlord was furious. He did not believe ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"The following day, impelled half by a wish to ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,On a small table in the room lay several pape...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,It is a pity that their yearning for posthumou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,We have hinted that Mrs. Trollope's strength ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"When she diverts her thoughts, she says, from ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,How vain are all the efforts which man is abl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,"In the opinion of one French critic, the book ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,"Everywhere, moreover, as one of her translator...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,France was not the only field of study which ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Our business in these pages is with Mrs. Troll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"In 1844 the industrious satirist, who would h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,This clever and industrious woman died at Flor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,William Henry Davenport Adams,bio12,MRS. TROLLOPE,Celebrated Women Travellers of the Nineteenth ...,Sonnenschein,Dutton,chapter

In [160]:
os.getcwd()

'/Users/user/Documents/capstone/data/books/a007'

In [161]:
os.listdir(path='/Users/user/Documents/capstone/data/books')

['a681',
 'a628',
 'a626',
 'a887',
 'a052A',
 'a221',
 'template folder for multiple bio folder creation',
 '.DS_Store',
 'a739',
 'a730',
 'a302A',
 'p091C',
 'a557',
 'a160',
 'TasteSearchProject.xpr',
 'a712',
 'a143',
 'a527',
 'a186',
 'a925',
 'template',
 'a007',
 'a894',
 'a001',
 'a270',
 'a020',
 'a624',
 'a411',
 'a282',
 'a813',
 'a221A',
 'p131A',
 'a162',
 'a793',
 'a788',
 'a920',
 'RCMCBWnewProject.xpr',
 'a789',
 'a319',
 'a185',
 'p067A',
 'a207',
 'a664',
 'a630',
 'a019A',
 'a468',
 'a034',
 'a607',
 'a095A',
 'a863',
 'ACCOMPLISHMENT.txt']

In [ ]:
os.cd